[[proxy]]
listener = "127.0.0.1:8080"

[proxy.servers.server1]
proxy_addr = "192.168.1.1"
proxy_tls = true
proxy_hostname = "server1"
proxy_headers = [[
    "Header1",
    "Value1",
]]

[[proxy]]
listener = "127.0.0.1:9090"
tls_certificate = "path/to/cert2" # Optional
tls_certificate_key = "path/to/key2" # Optional

[proxy.servers."proxy2.com"] # the name after the servers should match with proxy_hostname
proxy_addr = "192.168.1.2"
proxy_tls = false
proxy_hostname = "proxy2.com"
proxy_headers = [[
    "Header2",
    "Value2",
]]
