[[proxy]]
listener = "127.0.0.1:8080"
tls_certificate = "path/to/cert1"
tls_certificate_key = "path/to/key1"

[proxy.servers.server1]
proxy_addr = "192.168.1.1"
proxy_tls = true
proxy_hostname = "proxy1.com"
proxy_headers = [[
    "Header1",
    "Value1",
]]

[[proxy]]
listener = "127.0.0.1:9090"
tls_certificate = "path/to/cert2"
tls_certificate_key = "path/to/key2"

[proxy.servers.server2]
proxy_addr = "192.168.1.2"
proxy_tls = false
proxy_hostname = "proxy2.com"
proxy_headers = [[
    "Header2",
    "Value2",
]]
