[package]
name = "charon"
version = "0.1.0"
edition = "2024"

[dependencies]
pingora = { version = "0.4.0", features = ["proxy"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }
