[[proxy]]
listener = "0.0.0.0:80"

[proxy.servers."notls.domain.com"]
proxy_addr = "127.0.0.1:9690"
proxy_tls = false
proxy_hostname = "notls.domain.com"

[[proxy]]
listener = "0.0.0.0:443"
tls_certificate = "/etc/letsencrypt/live/kargate.site/fullchain.pem"
tls_certificate_key = "/etc/letsencrypt/live/kargate.site/privkey.pem"

[proxy.servers."backend.kargate.site"]
proxy_addr = "127.0.0.1:9691"
proxy_tls = false
proxy_hostname = "backend.kargate.site"

[proxy.servers."kargate.site"]
proxy_addr = "127.0.0.1:9696"
proxy_tls = false
proxy_hostname = "kargate.site"

[proxy.servers."landing.kargate.site"]
proxy_addr = "127.0.0.1:9696"
proxy_tls = false
proxy_hostname = "landing.kargate.site"

[proxy.servers."ssp.kargate.site"]
proxy_addr = "127.0.0.1:9699"
proxy_tls = false
proxy_hostname = "ssp.kargate.site"

[proxy.servers."wsa.kargate.site"]
proxy_addr = "127.0.0.1:9694"
proxy_tls = false
proxy_hostname = "wsa.kargate.site"

[proxy.servers."wsb.kargate.site"]
proxy_addr = "127.0.0.1:9692"
proxy_tls = false
proxy_hostname = "wsb.kargate.site"

[proxy.servers."wsio.kargate.site"]
proxy_addr = "127.0.0.1:9697"
proxy_tls = false
proxy_hostname = "wsio.kargate.site"

[proxy.servers."www.kargate.site"]
proxy_addr = "127.0.0.1:9696"
proxy_tls = false
proxy_hostname = "www.kargate.site"
